FROM gcr.io/tensorflow/tensorflow:1.2.1-gpu-py3

# Update OS
RUN sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list
RUN apt-get update
RUN apt-get -y upgrade

# Enable Jupyter JS Extensions
RUN jupyter nbextension enable --py widgetsnbextension

# Add requirements.txt
ADD requirements.txt .
 
# Install app requirements
RUN pip install -r requirements.txt

